name: pretransplant_pgx
version: "1.0.0"
config-version: 2

profile: pretransplant_pgx

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  pretransplant_pgx:
    staging:
      +materialized: view
    marts:
      +materialized: table
